[GLOBAL]
pants_version = "2.19.1"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy"
]

[python]
interpreter_constraints = [">=3.11,<3.12"]
enable_resolves = true

[python-bootstrap]
search_path = ["<PYENV>", "<PATH>"]

[python.resolves]
ynab_homeassistant = "3rdparty/python/ynab_homeassistant.lock"

[export]
resolve = [
    "ynab_homeassistant",
]

[flake8]
config = ".flake8"

[isort]
config = ["pyproject.toml"]