python_sources(
    name="lib",
    resolve="ynab_homeassistant",
    sources=["**/*.py"],
)

python_requirements(
    source="requirements.txt",
    resolve="ynab_homeassistant",
    module_mapping={"ynab-python": ["ynab"]},
)